version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: hackathon
    ports:
      - 5432:5432
volumes:
  pgdata:
